# Generated by Django 5.1.3 on 2025-03-27 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pessoas", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Pessoas",
            new_name="Pessoa",
        ),
    ]
