# Generated by Django 5.1.3 on 2025-03-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="capa",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="banda",
            name="ano_criacao",
            field=models.IntegerField(default=2000, verbose_name="Ano de criação"),
        ),
        migrations.AddField(
            model_name="banda",
            name="descricao",
            field=models.CharField(
                default="Inserir Descrição", max_length=1000, verbose_name="Descrição"
            ),
        ),
        migrations.AddField(
            model_name="banda",
            name="foto_banda",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="musica",
            name="letra",
            field=models.CharField(default="Inserir Letra", max_length=1000),
        ),
        migrations.AddField(
            model_name="musica",
            name="link",
            field=models.URLField(
                blank=True,
                db_index=True,
                max_length=128,
                unique=True,
                verbose_name="URL da música",
            ),
        ),
    ]
