# Generated by Django 5.1.3 on 2025-03-27 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandas", "0002_album_capa_banda_ano_criacao_banda_descricao_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banda",
            name="descricao",
            field=models.CharField(
                default=None, max_length=1000, verbose_name="Descrição"
            ),
        ),
        migrations.AlterField(
            model_name="musica",
            name="banda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mússicas",
                to="bandas.banda",
            ),
        ),
        migrations.AlterField(
            model_name="musica",
            name="letra",
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
