# Generated by Django 5.1.3 on 2025-03-27 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandas", "0003_alter_banda_descricao_alter_musica_banda_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musica",
            name="banda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="músicas",
                to="bandas.banda",
            ),
        ),
    ]
