# Generated by Django 5.1.3 on 2025-03-27 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandas", "0004_alter_musica_banda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musica",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="álbuns",
                to="bandas.album",
            ),
        ),
    ]
