# Generated by Django 5.1.3 on 2025-03-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandas", "0006_alter_album_banda_alter_musica_album_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banda",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="banda",
            name="foto_banda",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Foto da banda"
            ),
        ),
        migrations.AlterField(
            model_name="musica",
            name="letra",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="musica",
            name="link",
            field=models.URLField(
                blank=True,
                db_index=True,
                max_length=128,
                null=True,
                unique=True,
                verbose_name="URL da música",
            ),
        ),
    ]
