# Generated by Django 5.1.3 on 2025-04-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandas", "0007_alter_banda_descricao_alter_banda_foto_banda_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="capa",
            field=models.ImageField(blank=True, null=True, upload_to="bandas/capas"),
        ),
        migrations.AlterField(
            model_name="banda",
            name="foto_banda",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="bandas/fotos",
                verbose_name="Foto da banda",
            ),
        ),
    ]
