# Generated by Django 5.1.3 on 2025-04-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandas", "0008_alter_album_capa_alter_banda_foto_banda"),
    ]

    operations = [
        migrations.AddField(
            model_name="banda",
            name="nacionalidade",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="musica",
            name="duracao",
            field=models.DecimalField(
                decimal_places=2, max_digits=4, null=True, verbose_name="Duração"
            ),
        ),
    ]
