# Generated by Django 5.1.3 on 2025-04-03 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandas", "0009_banda_nacionalidade_musica_duracao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musica",
            name="duracao",
            field=models.DurationField(null=True, verbose_name="Duração"),
        ),
    ]
