# Generated by Django 5.1.3 on 2025-04-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandas", "0010_alter_musica_duracao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banda",
            name="nacionalidade",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="musica",
            name="duracao",
            field=models.DurationField(verbose_name="Duração"),
        ),
    ]
