# Generated by Django 5.1.3 on 2025-04-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandas", "0012_album_ano_lancamento_alter_banda_ano_criacao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="album",
            name="ano_lancamento",
            field=models.IntegerField(verbose_name="Ano de lançamento"),
        ),
    ]
