# Generated by Django 5.1.3 on 2025-04-03 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bandas", "0013_alter_album_ano_lancamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="musica",
            name="album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="musicas",
                to="bandas.album",
            ),
        ),
    ]
