# Generated by Django 5.1.3 on 2025-04-21 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="projetos/logos"
                    ),
                ),
                ("descricao", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("link_moodle", models.URLField(blank=True, null=True)),
                (
                    "link_pagina_ulusofona",
                    models.URLField(
                        blank=True, null=True, verbose_name="Link página ULusofona"
                    ),
                ),
                (
                    "docentes",
                    models.ManyToManyField(
                        related_name="disciplinas", to="portfolio.docente"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("link_itch", models.URLField(blank=True, null=True)),
                ("link_github", models.URLField(blank=True, null=True)),
                ("link_video", models.URLField(blank=True, null=True)),
                (
                    "aspetos_tecnicos",
                    models.TextField(
                        blank=True, null=True, verbose_name="Aspectos técnicos"
                    ),
                ),
                ("conceitos_aplicados", models.TextField()),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projetos",
                        to="portfolio.disciplina",
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        related_name="projetos", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImagemProjeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.ImageField(upload_to="projetos/imagens")),
                ("legenda", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "projeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagens",
                        to="portfolio.projeto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FichaTecnica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plataforma", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "duracao_desenvolvimento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Duração do desenvolvimento",
                    ),
                ),
                (
                    "equipa",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        verbose_name="Número de elementos na equipa",
                    ),
                ),
                (
                    "projeto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ficha_tecnica",
                        to="portfolio.projeto",
                    ),
                ),
            ],
        ),
    ]
