# Generated by Django 5.1.3 on 2025-04-22 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tecnologia",
            old_name="logo",
            new_name="logotipo",
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="descricao",
            field=models.TextField(verbose_name="Descrição"),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="descricao",
            field=models.TextField(verbose_name="Descrição"),
        ),
    ]
