# Generated by Django 5.1.3 on 2025-05-14 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_rename_logo_tecnologia_logotipo_tecnologia_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visitante",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.GenericIPAddressField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="projeto",
            name="disciplina",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projetos",
                to="portfolio.disciplina",
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="projetos",
                to="portfolio.tecnologia",
            ),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="link",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="logotipo",
            field=models.ImageField(upload_to="projetos/logos"),
        ),
    ]
