# Generated by Django 5.1.3 on 2025-05-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_visitante_alter_projeto_disciplina_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="aspetos_tecnicos",
            field=models.TextField(verbose_name="Aspectos técnicos"),
        ),
    ]
