# Generated by Django 5.1.3 on 2025-05-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_alter_projeto_aspetos_tecnicos"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitante",
            name="session_key",
            field=models.CharField(default=21312, max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="visitante",
            name="ip",
            field=models.GenericIPAddressField(),
        ),
    ]
