# Generated by Django 5.1.3 on 2025-05-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_visitante_session_key_alter_visitante_ip"),
    ]

    operations = [
        migrations.RenameField(
            model_name="visitante",
            old_name="session_key",
            new_name="session_keyy",
        ),
    ]
