# Generated by Django 5.1.3 on 2025-05-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_rename_session_key_visitante_session_keyy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitante",
            name="session_keyy",
        ),
        migrations.AddField(
            model_name="visitante",
            name="session_keyyy",
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
