# Generated by Django 5.1.3 on 2025-05-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_remove_visitante_session_keyy_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visitante",
            name="session_keyyy",
        ),
        migrations.AddField(
            model_name="visitante",
            name="session_key",
            field=models.CharField(default=1, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
