# Generated by Django 5.1.3 on 2025-05-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_alter_projeto_tecnologias"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interesse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(verbose_name="Descrição")),
                (
                    "disciplinas",
                    models.ManyToManyField(
                        related_name="interesses", to="portfolio.disciplina"
                    ),
                ),
                (
                    "projetos",
                    models.ManyToManyField(
                        related_name="interesses", to="portfolio.projeto"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(
                        related_name="interesses", to="portfolio.tecnologia"
                    ),
                ),
            ],
        ),
    ]
