# Generated by Django 5.1.3 on 2025-06-14 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_interesse"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Visitante",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
        migrations.DeleteModel(
            name="Interesse",
        ),
    ]