# Generated by Django 5.2.1 on 2025-06-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_add_ordem_to_projeto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['ordem', 'titulo']},
        ),
    ]
