# Generated by Django 5.2.1 on 2025-06-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_alter_projeto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='my_role',
            field=models.TextField(blank=True, help_text='Describe your specific role and contributions to this project', null=True, verbose_name='My Role & Contribution'),
        ),
    ]
