# Generated by Django - Migration Corrigida

from django.db import migrations, models
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    """Popula os slugs para os objetos existentes"""
    Projeto = apps.get_model('portfolio', 'Projeto')
    Tecnologia = apps.get_model('portfolio', 'Tecnologia')
    
    # Gerar slugs para projetos existentes
    for projeto in Projeto.objects.all():
        if not projeto.slug:
            base_slug = slugify(projeto.titulo)
            slug = base_slug
            counter = 1
            
            # Garantir que o slug é único
            while Projeto.objects.filter(slug=slug).exclude(pk=projeto.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            projeto.slug = slug
            projeto.save()
    
    # Gerar slugs para tecnologias existentes
    for tecnologia in Tecnologia.objects.all():
        if not tecnologia.slug:
            base_slug = slugify(tecnologia.nome)
            slug = base_slug
            counter = 1
            
            # Garantir que o slug é único
            while Tecnologia.objects.filter(slug=slug).exclude(pk=tecnologia.pk).exists():
                slug = f"{base_slug}-{counter}"
                counter += 1
            
            tecnologia.slug = slug
            tecnologia.save()

def reverse_populate_slugs(apps, schema_editor):
    """Função reversa para desfazer a migration"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_projeto_my_role'),
    ]

    operations = [
        # Primeiro: Adicionar campos slug SEM unique=True
        migrations.AddField(
            model_name='projeto',
            name='slug',
            field=models.SlugField(
                blank=True, 
                null=True,
                help_text='URL amigável gerada automaticamente a partir do título'
            ),
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='slug',
            field=models.SlugField(
                blank=True, 
                null=True,
                help_text='URL amigável gerada automaticamente a partir do nome'
            ),
        ),
        # Segundo: Popular os slugs
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
        # Terceiro: Tornar os campos únicos DEPOIS de serem populados
        migrations.AlterField(
            model_name='projeto',
            name='slug',
            field=models.SlugField(
                unique=True,
                help_text='URL amigável gerada automaticamente a partir do título'
            ),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='slug',
            field=models.SlugField(
                unique=True,
                help_text='URL amigável gerada automaticamente a partir do nome'
            ),
        ),
    ]