# Generated by Django 5.2.1 on 2025-06-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_projeto_tecnologia_individual'),
        ('portfolio', '0019_award'),
    ]

    operations = [
    ]
