# Generated by Django 6.0.2 on 2026-03-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_merge_0018_projeto_tecnologia_individual_0019_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='curso',
            field=models.CharField(choices=[('bachelor', 'Bachelor in Videogames'), ('msc', 'MSc in Artificial Intelligence for Games')], default='bachelor', max_length=20),
        ),
    ]
