# Generated by Django 6.0.2 on 2026-03-15 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_disciplina_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='docentes',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='link_moodle',
        ),
        migrations.RemoveField(
            model_name='disciplina',
            name='link_pagina_ulusofona',
        ),
    ]
