# Generated by Django 6.0.2 on 2026-03-15 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_remove_disciplina_docentes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
