# Generated by Django 5.1.3 on 2025-03-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0002_alter_comentario_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="data",
            field=models.DateField(verbose_name="Data de publicação"),
        ),
    ]
