# Generated by Django 5.1.3 on 2025-03-29 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0003_alter_post_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autor",
            name="nome_utilizador",
        ),
    ]
