# Generated by Django 5.1.3 on 2025-03-29 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0005_alter_comentario_nome_comentador"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="comentario_pai",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respostas",
                to="artigos.comentario",
            ),
        ),
    ]
