# Generated by Django 5.1.3 on 2025-04-03 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0006_comentario_comentario_pai"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="foto_perfil",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="bandas/fotosperfil",
                verbose_name="Foto de Perfil",
            ),
        ),
        migrations.AlterField(
            model_name="comentario",
            name="comentario_pai",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="respostas",
                to="artigos.comentario",
                verbose_name="Comentário pai",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="imagem_capa",
            field=models.ImageField(blank=True, null=True, upload_to="artigos/capas"),
        ),
    ]
