# Generated by Django 5.1.3 on 2025-04-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0007_alter_autor_foto_perfil_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="foto_perfil",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="artigos/fotosperfil",
                verbose_name="Foto de Perfil",
            ),
        ),
    ]
